system:
  title: 'Flatlogin'
  theme: 'default'
  register: true
mail:
  from: 'mail@mail.ch'
  from_name: FIRMA
  host: ''
  pass: ''
  port: 465
  smtp:
    auth: 1
    secure: ssl
  type: sendmail
  user: ''
twig:
  cache:
    enabled: false
secure:
  ip:
    enabled: false
    allowed:
      - '::1'
  ssl:
    force: false
  captcha:
    enabled: false
    version: '2'
    url: https://www.google.com/recaptcha/api/siteverify
    key:
      private: 'PRIVATEKEY'
      public: 'PUBLICKEY'
